export BIAS_MODEL_DEVICE=cpu

# To run the plotting command separately, comment out the unwanted command lines
# plotting for NoiseLevels excluding noise level 1
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_Poster_Exculde1.py UNIFORM_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_Poster_Exculde1.py STEEPPERIODIC_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_Poster_Exculde1.py STEEPSHIFTED_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_Poster_Exculde1.py STEEPPERIODIC_UNIFORM

rm output/evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat.py.txt
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat.py UNIFORM_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat.py STEEPPERIODIC_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat.py STEEPSHIFTED_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat.py STEEPPERIODIC_UNIFORM

rm output/evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat_Lp.py.txt
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat_Lp.py UNIFORM_STEEPPERIODIC 2
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat_Lp.py STEEPPERIODIC_STEEPPERIODIC 2
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat_Lp.py STEEPSHIFTED_STEEPPERIODIC 2
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat_Lp.py STEEPPERIODIC_UNIFORM 2
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat_Lp.py UNIFORM_STEEPPERIODIC 8
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat_Lp.py STEEPPERIODIC_STEEPPERIODIC 8
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat_Lp.py STEEPSHIFTED_STEEPPERIODIC 8
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_JustCollStat_Lp.py STEEPPERIODIC_UNIFORM 8




## plotting for NoiseLeveks excluding noise level 1
#python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_Poster.py UNIFORM_STEEPPERIODIC
#python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_Poster.py STEEPPERIODIC_STEEPPERIODIC 
#python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_Poster.py STEEPSHIFTED_STEEPPERIODIC



# plotting without Guesses

python3 evaluateCrossValidationResults_Synthetic_Gardelle_NoGuess_ButMotor_VisualizeByNoiseCount_AndSize_ByP_Poster_Exculde1.py UNIFORM_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_NoGuess_ButMotor_VisualizeByNoiseCount_AndSize_ByP_Poster_Exculde1.py STEEPPERIODIC_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_NoGuess_ButMotor_VisualizeByNoiseCount_AndSize_ByP_Poster_Exculde1.py STEEPSHIFTED_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_NoGuess_ButMotor_VisualizeByNoiseCount_AndSize_ByP_Poster_Exculde1.py STEEPPERIODIC_UNIFORM




rm output/evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_ConfusMat.py.txt
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_ConfusMat.py UNIFORM_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_ConfusMat.py STEEPPERIODIC_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_ConfusMat.py STEEPSHIFTED_STEEPPERIODIC
python3 evaluateCrossValidationResults_Synthetic_Gardelle_VisualizeByNoiseCount_AndSize_ByP_ConfusMat.py STEEPPERIODIC_UNIFORM


