export BIAS_MODEL_DEVICE=cpu

# To run the data sampling command separately, comment out the unwanted command lines
# data sampling for P=0
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_ZeroTrig_ALL.py STEEPPERIODIC STEEPPERIODIC
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_ZeroTrig_ALL.py STEEPSHIFTED STEEPPERIODIC
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_ZeroTrig_ALL.py UNIFORM STEEPPERIODIC
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_ZeroTrig_ALL.py STEEPPERIODIC UNIFORM

# data sampling for P=1
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_L1_ALL.py STEEPPERIODIC STEEPPERIODIC
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_L1_ALL.py STEEPSHIFTED STEEPPERIODIC
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_L1_ALL.py UNIFORM STEEPPERIODIC
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_L1_ALL.py STEEPPERIODIC UNIFORM

# data sampling for P=2,4,6,8
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_ALL.py STEEPPERIODIC STEEPPERIODIC
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_ALL.py STEEPSHIFTED STEEPPERIODIC
python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_ALL.py UNIFORM STEEPPERIODIC

python3 SimulateSynthetic_Parameterized_OtherNoiseLevels_Grid_VarySize_ALL.py STEEPPERIODIC UNIFORM



